project_id = "nwyvkqqbdqigsimdzzrg"

[functions.dashboard]
verify_jwt = false

[functions.session]
verify_jwt = false

[functions.tec-sync]
verify_jwt = false

[functions.events]
verify_jwt = false

[functions.plan]
verify_jwt = false
