/* Local-only reader: paid PDFs are selected by the student and never uploaded. */
(() => {
  'use strict';
  const F={p1:'PARTE+1+FGV+RESUMO+RETA+FINAL+DATAPREV+DEV.pdf',p2:'PARTE+2+FGV+RESUMO+RETA+FINAL+DATAPREV+DEV.pdf'};
  const a=(p,e,t)=>({f:'p1',p,e,t}),b=(p,e,t)=>({f:'p2',p,e,t});
  // Mappings independently checked in the FGV Capivara edition. No link means no claimed coverage.
  const M={E03:[a(6,9,'SOA, web services e API')],E04:[a(12,14,'OO e arquitetura web')],E05:[a(32,37,'Scrum, Kanban e XP')],E06:[a(51,56,'HTML e frontend')],E07:[a(72,87,'IA, análise de dados e Big Data')],E08:[b(30,48,'DW, BI, OLAP e ETL/ELT')],E09:[a(88,98,'SGSI e ISO 27001/27002')],E10:[b(2,24,'Modelagem, relacional e normalização')],E11:[b(2,24,'SQL, DDL e DML')],E12:[b(92,104,'Governança e COBIT')],E13:[b(82,104,'BPM, BPMN e governança')],E14:[a(57,61,'HTTPS, SSL e TLS'),a(88,98,'Segurança aplicada')],E15:[a(15,15,'Servidor web x aplicação'),a(17,19,'XML, XSLT e JSON'),a(51,56,'SPA e PWA'),a(62,66,'Arquitetura e microsserviços')],E16:[a(41,45,'Análise de Pontos de Função')],E17:[a(24,31,'Testes, TDD e automação')],E18:[a(46,50,'Engenharia e elicitação de requisitos')],E19:[a(20,23,'DevOps')],E20:[a(38,40,'Padrões de desenvolvimento e reuso')],E21:[a(32,37,'Scrum, Kanban e XP')],E22:[b(66,81,'Projetos e gestão híbrida')],E23:[a(88,98,'Segurança da informação')],E24:[a(88,98,'ISO 27001/27002 e controles')],E25:[a(3,5,'Clean Code e análise estática')],E26:[a(3,5,'SonarQube e análise estática')],E40:[a(10,11,'Internet, intranet, extranet e portal')],E41:[a(51,56,'Frameworks frontend')],E42:[a(51,56,'Frameworks frontend')],E43:[a(67,71,'Arquitetura da informação e UX')],E44:[a(67,71,'Usabilidade e UX')],E45:[a(67,71,'Acessibilidade e usabilidade')],E46:[b(30,48,'BI e sistemas de apoio à decisão')],E47:[a(72,87,'IA, mineração e análise')],E48:[a(72,87,'IA e ML'),b(49,65,'IA e aprendizado de máquina')],E49:[b(49,65,'IA generativa e dados')],E50:[b(25,29,'NoSQL')],E51:[b(82,91,'ITIL 4')],E52:[b(66,81,'Gerenciamento de projetos')],E54:[a(17,19,'XML, XSLT, UDDI, REST e JSON')],E55:[a(51,56,'SPA')],E56:[a(51,56,'PWA')],E58:[a(62,66,'Microsserviços e API gateway')],E61:[a(67,71,'Portais corporativos')],E62:[a(67,71,'CMS')],E63:[a(62,66,'Arquitetura hexagonal')],E64:[a(57,61,'Blockchain e segurança')],E65:[b(2,29,'Banco de dados e NoSQL')],E66:[a(67,71,'Workflow e processos')],E67:[b(2,29,'Formatos e modelagem de dados')],E68:[a(20,30,'DevOps e Git')],E69:[a(62,66,'Contêineres e orquestração')],E70:[a(57,61,'HTTPS, SSL e TLS')],E72:[a(12,15,'Arquitetura e design de software')],E73:[a(46,50,'Elicitação e gestão de requisitos')]};
  M.E74=[a(51,56,'Ajax e tecnologias frontend')];
  const DB='nexame-local-materials',STORE='handles',KEY='study-pdf-folder'; let dir,url;
  const database=()=>new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
  async function saved(){if(dir)return dir;const d=await database();dir=await new Promise((ok,no)=>{const t=d.transaction(STORE);const r=t.objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)});return dir}
  async function store(x){const d=await database();await new Promise((ok,no)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(x,KEY);t.oncomplete=ok;t.onerror=()=>no(t.error)});dir=x}
  async function choose(){if(!window.showDirectoryPicker)throw Error('Navegador sem seleção segura de pasta');const x=await window.showDirectoryPicker({mode:'read',id:'nexame-study-pdfs'});await store(x);return x}
  async function access(x){return x&&((await x.queryPermission({mode:'read'}))==='granted'||(await x.requestPermission({mode:'read'}))==='granted')}
  function close(){const d=document.querySelector('#nexame-pdf-reader');if(d?.open)d.close();if(url){URL.revokeObjectURL(url);url=null}}
  function dialog(){let d=document.querySelector('#nexame-pdf-reader');if(d)return d;d=document.createElement('dialog');d.id='nexame-pdf-reader';d.style.cssText='width:min(1120px,94vw);height:min(88vh,920px);padding:0;border:1px solid #26384f;border-radius:12px;background:#101d2f;color:#eef5ff';d.innerHTML='<div class="nexame-reader-head" style="height:52px;display:flex;align-items:center;justify-content:space-between;padding:10px 14px;border-bottom:1px solid #26384f"><strong></strong><button type="button">Fechar</button></div><iframe title="Leitor do material de revisão" style="width:100%;height:calc(100% - 52px);border:0;background:#fff"></iframe>';d.querySelector('button').onclick=close;d.onclose=()=>{if(url){URL.revokeObjectURL(url);url=null}};document.body.append(d);return d}
  async function open(x){try{let h=await saved();if(!(await access(h)))h=await choose();const file=await (await h.getFileHandle(F[x.f])).getFile();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);const d=dialog();d.querySelector('strong').textContent=`${x.t} · p. ${x.p}${x.e!==x.p?`–${x.e}`:''}`;d.querySelector('iframe').src=`${url}#page=${x.p}&view=FitH`;d.showModal()}catch(e){if(e?.name!=='AbortError')alert(`Não foi possível abrir o PDF. Escolha a pasta que contém “${F[x.f]}”.`)}}
  function render(code,target=document){const s=target.querySelector('#materials');if(!s)return;s.replaceChildren();const items=M[code]||[];if(!items.length)return;const title=target.createElement('b');title.textContent='Revisar no seu PDF';const note=target.createElement('span');note.className='small nexame-material-note';note.textContent='Abre a página exata do seu resumo local.';const links=target.createElement('div');links.className='nexame-material-links';items.forEach(x=>{const q=target.createElement('button');q.type='button';q.className='nexame-material-link';q.textContent=`${x.t} · p. ${x.p}${x.e!==x.p?`–${x.e}`:''}`;q.onclick=()=>open(x);links.append(q)});const manage=target.createElement('button');manage.type='button';manage.className='nexame-material-manage';manage.textContent='Vincular outra pasta';manage.onclick=async()=>{try{await choose();render(code,target)}catch(e){if(e?.name!=='AbortError')alert('Não foi possível vincular a pasta de PDFs.')}};s.append(title,note,links,manage)}
  function attach(target,code){if(!target)return;if(!target.querySelector('#nexame-material-style')){const css=target.createElement('style');css.id='nexame-material-style';css.textContent='.materials{margin-top:10px;padding-top:10px;border-top:1px solid #26384f}.materials b,.materials .nexame-material-note{display:block}.nexame-material-links{display:grid;gap:7px;margin-top:8px}.nexame-material-link,.nexame-material-manage{width:100%;text-align:left;background:#17364e;color:#cceeff;border:1px solid #35677f;border-radius:7px;padding:8px;cursor:pointer}.nexame-material-manage{width:auto;margin-top:8px;background:transparent;color:#9fb0c7;font-size:.78rem;padding:5px 7px}';target.head.append(css)}let s=target.querySelector('#materials');const tec=target.querySelector('#tec');if(!s&&tec){s=target.createElement('div');s.id='materials';s.className='tec materials';tec.insertAdjacentElement('afterend',s)}render(code,target)}
  window.NexamePdfLibrary={render,attach,close};
})();
